theme: minima
title: Kinolee Kumarasinghe
author: Kinolee Kumarasinghe
email: klkumarasinghe@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is where you can reach out to me!

# social links
instagram_username: _k.kumarasinghe # DO NOT include the @ character, or else the build will fail!
github_username:  klkumarasinghe # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
