theme: modernist
title: Kinolee Kumarasinghe's Blog
author: Kinolee Kumarasinghe
email: klkumarasinghe@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
instagram_username: _k.kumarasinghe # DO NOT include the @ character, or else the build will fail!
github_username:  klkumarasinghe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
